### ISSUE TITLE
[bugs] Issues with backend validations

### ISSUE THREAD

**Issue by Aviral14** [ccit-bphc/ccit-portal#112]
1.No complaint can be cancelled,resolved etc as there is a bug in validation
2.Improper validation message is shown when user fills up the unblock request form incorrectly.

**Comment by Kushagra-0801** [comment]
How exactly did you fill up the unblock request form incorrectly?

**Comment by Aviral14** [comment]
with an invalid tld

**Comment by Kushagra-0801** [comment]
Should I just forward the validation error message to the form?

**Comment by Kushagra-0801** [comment]
forget it. some of them are not user friendly
