### ISSUE TITLE
Bug: Problems in Templates

### ISSUE THREAD

**Issue by Kushagra-0801** [ccit-bphc/ccit-portal#28]
Code Quality Issues
1. Tags are not balanced
2. Inheritance is not used
3. Reverse lookup is not used in many places
4. Url field in unblock request form does not call the checkurl function
5. Id attribute is same for a lot of elements
6. Client side validation is sorely missing
7. Input type `time` and `date` are not supported in firefox and need to be changed to some other form.
8. Complaint resolution by staff and list of complaints of user, both are different things, and need to stay different
9. There are a lot of junk files, like `login1.html`, `login11.html`, `previous-request-old.html` etc

**Comment by Aviral14** [comment]
Some Suggestions for UI-
1.Increase Navbar size
2.CCIT logo to be shifted in left and size increased.
3.Nav bar text size is not uniform
4.Navbar buttons' background  not getting highlighted on hover.
5.Messages not properly placed.
6.Urgency button looks like its already filled.
7.Color of details not correct.

**Comment by Aviral14** [comment]
@iamkroot Please test the code on frontend branch and give reviews.

**Comment by Aviral14** [comment]
@0xVikas What's the update on this issue?
