### ISSUE TITLE
Bug: Multiple issues

### ISSUE THREAD

**Issue by Kushagra-0801** [ccit-bphc/ccit-portal#43]
1. Navbar is broken on some pages
2. URL helper function (the one that adds a protocol in its absence) is not working
3. HTML is broken on a lot of pages
4. `Remarks to user` is an editable text field
5.  Cancel button appears above the table in user's `my complaints`
6. `My complaints` does not show the `url unblock requests`.

**Comment by Kushagra-0801** [comment]
7. Cancel button on a normal user's complaint sends the request to the staff users' resolve page

**Comment by Kushagra-0801** [comment]
There are a lot of problems with having a single template with a big if-else for both a normal user and a staff user. Make two separate templates. The right one will be called by the backend

**Comment by Aviral14** [comment]
@0xVikas I have added messages for invalid sign in on the login page.Please style that message and put it at the proper position.

**Comment by Aviral14** [comment]
@0xVikas  Please add proper validations for the form data in the frontend.

**Comment by 0xVikas** [comment]
@Kushagra-0801 Points 4,5,6 & 7 are because the user is a superuser. I can't do anything about that. And what do you mean by html is broken ? Please elaborate on ponits 1,2,3

**Comment by iamkroot** [comment]
> Points 4,5,6 & 7 are because the user is a superuser.

We should still ensure that the page is rendered properly for every type of user. In case of superuser, we can show them the same view as staff.

**Comment by Kushagra-0801** [comment]
@0xVikas 
For 2, The URL field expects the protocol to be present in the url. No one is gonna do that. So the function was supposed to add a default `https` protocol to any url where it isn't present.
For 7, I tried with a normal user, it showed up like that.
For 4, `Remarks to User` shouldn't be an editable field for a non staff user
For 5, The cancel button should be along with the complaint. No difference if the user is superuser, normal user or whatever. That's a frontend thing. You did not make the table correctly.
