### ISSUE TITLE
Change client side regex to match the one used in the backend

### ISSUE THREAD

**Issue by Kushagra-0801** [ccit-bphc/ccit-portal#63]
1. The regex used in `main.js` to validate contact number is different from the one used in backend. Change the one in `main.js` to match the `PHONE_REGEX` in `Complaint` model.
2. The function checking for protocol presence in url only checks for http and https. Change it to check for any protocol (just check for `://`, don't worry if the protocol is valid or not).
3. There are some useless comments in `('#option').change`. Remove them.

**Comment by Kushagra-0801** [comment]
Do we have standard format for room numbers?

**Comment by 0xVikas** [comment]
URL checking is changed, now it looks only for the "://" part. And the comments in ('#option').change are necessary for any future changes.

**Comment by Kushagra-0801** [comment]
okay

**Comment by Aviral14** [comment]
@Kushagra-0801 if this issue has been sorted out then please close it!
