### ISSUE TITLE
Issue with Availibility timing for girls

### ISSUE THREAD

**Issue by Aviral14** [ccit-bphc/ccit-portal#81]
1.4:30-5:30 slot is being sent to backend as 4:30 am to 5:30 am
2.12 to 1:30 slot not being accepted at the backend.

**Comment by Aviral14** [comment]
@0xVikas @Kushagra-0801 Please sort out this issue

**Comment by Kushagra-0801** [comment]
The problem is with the value of the end time. It is set to `1:30`, `4:30`, `5:30` They need to be `13:30`, `16:30`, `17:00` (or is it 17:30? Confirm with someone)
@0xVikas  This is your thing. Also make the choices radio buttons or let the students select both of them

**Comment by Kushagra-0801** [comment]
There is still the 1 hr limit in code. Tell me if it needs to be removed or tweaked or something

**Comment by Aviral14** [comment]
Closed in #92
